create table film_entity (
                             id integer generated by default as identity not null ,
                             description varchar(1048),
                             film_id integer,
                             film_name varchar(255),
                             rating float,
                             year integer,
                             primary key (id)
);